language: generic
dist: trusty
os: linux

notifications:
  email:
    on_failure: always
    recipients:
      - a.gutenkunst@pilz.de
env:
  global:
    - ROS_DISTRO="melodic"
    - BUILDER="colcon"
    - CODE_COVERAGE="term"
  matrix:
    - ROS_REPO=main
install:
  - git clone --quiet --depth 1 https://github.com/Briancbn/industrial_ci.git .industrial_ci -b pr-coverage
script:
  - .industrial_ci/travis.sh